SELECT '合计',
       null,
       nvl(sum(r4.cost), 0),
       nvl(sum(r4.real_cost), 0),
       nvl(sum(r4.show_count), 0),
       nvl(sum(r4.click_count), 0),
       f_divide_to_percent_str(sum(r4.click_count), sum(r4.show_count), 4),
       nvl(sum(r4.convert_count), 0),
       f_divide_to_percent_str(sum(r4.convert_count),
                               sum(r4.click_count),
                               4),
       f_divide(sum(r4.cost), sum(r4.convert_count)),
       nvl(sum(r4.total_order_count), 0),
       nvl(sum(r4.valid_order_count), 0),
       f_divide_to_percent_str(sum(r4.valid_order_count),
                               sum(r4.total_order_count),
                               4),
       f_divide(sum(r4.real_cost), sum(r4.valid_order_count)),
       nvl(sum(r4.express_count), 0),
       f_divide_to_percent_str(sum(r4.express_count),
                               sum(r4.valid_order_count),
                               4),
       nvl(sum(r4.activate_count), 0),
       f_divide_to_percent_str(sum(r4.activate_count),
                               sum(r4.total_order_count),
                               4),
       f_divide_to_percent_str(sum(r4.activate_count),
                               sum(r4.valid_order_count),
                               4),
       nvl(sum(r4.activate_t3_count), 0),
       f_divide_to_percent_str(sum(r4.activate_t3_count),
                               sum(r4.valid_order_count),
                               4),
       nvl(sum(r4.activate_t7_count), 0),
       f_divide_to_percent_str(sum(r4.activate_t7_count),
                               sum(r4.valid_order_count),
                               4),
       f_divide(sum(r4.real_cost), sum(r4.activate_count), 2),
       nvl(sum(r4.recharge_count), 0),
       f_divide_to_percent_str(sum(r4.recharge_count),
                               sum(r4.valid_order_count),
                               4),
       nvl(sum(r4.expected_income), 0),
       null,
       nvl(nvl(sum(r4.expected_income), 0) - nvl(sum(r4.real_cost), 0), 0),
       f_divide(sum(r4.expected_income), sum(r4.real_cost), 2),
       nvl(sum(r4.open_cnt), 0),
       nvl(sum(r4.input_tel), 0),
       f_divide_to_percent_str(sum(r4.input_tel), sum(r4.open_cnt), 4),
       nvl(sum(r4.click_code), 0),
       f_divide_to_percent_str(sum(r4.click_code), sum(r4.input_tel), 4),
       nvl(sum(r4.input_code), 0),
       f_divide_to_percent_str(sum(r4.input_code), sum(r4.click_code), 4),
       nvl(sum(r4.click_check), 0),
       f_divide_to_percent_str(sum(r4.click_check), sum(r4.click_code), 4),
       nvl(sum(r4.click_sub), 0),
       f_divide_to_percent_str(sum(r4.click_sub), sum(r4.click_check), 4),
       nvl(sum(r4.load_img_time), 0),
       f_divide(sum(r4.load_img_time), sum(r4.open_cnt) * 1000, 2)
  FROM r4;