exports.config = {
	aditionalOption: {
		add: true,
		addBatch: false,
		deleteById: true,
		deleteBatch: false,
		updateById: true,
		updateBatch: false,
		getById: false,
		getPage: false,
		getDetailById: false,
		getAll: false,
		count: false,
		getDetailPage: true
	},
	dictionary: {
		add: true,
		addBatch: false,
		deleteById: true,
		deleteBatch: false,
		updateById: true,
		updateBatch: false,
		getById: false,
		getPage: false,
		getDetailById: false,
		getAll: false,
		count: false,
		getDetailPage: true
	},
	fieldInfo: {
		add: true,
		addBatch: false,
		deleteById: true,
		deleteBatch: false,
		updateById: true,
		updateBatch: false,
		getById: false,
		getPage: false,
		getDetailById: false,
		getAll: false,
		count: false,
		getDetailPage: true
	},
	moduleS: {
		add: true,
		addBatch: false,
		deleteById: true,
		deleteBatch: false,
		updateById: true,
		updateBatch: false,
		getById: false,
		getPage: false,
		getDetailById: false,
		getAll: false,
		count: false,
		getDetailPage: true
	},
	project: {
		add: true,
		addBatch: false,
		deleteById: true,
		deleteBatch: false,
		updateById: true,
		updateBatch: false,
		getById: false,
		getPage: false,
		getDetailById: false,
		getAll: false,
		count: false,
		getDetailPage: true
	},
	tableInfo: {
		add: true,
		addBatch: false,
		deleteById: true,
		deleteBatch: false,
		updateById: true,
		updateBatch: false,
		getById: false,
		getPage: false,
		getDetailById: false,
		getAll: false,
		count: false,
		getDetailPage: true
	},
	themeConfig: {
		add: true,
		addBatch: false,
		deleteById: true,
		deleteBatch: false,
		updateById: true,
		updateBatch: false,
		getById: false,
		getPage: false,
		getDetailById: false,
		getAll: false,
		count: false,
		getDetailPage: true
	},
	validator: {
		add: true,
		addBatch: false,
		deleteById: true,
		deleteBatch: false,
		updateById: true,
		updateBatch: false,
		getById: false,
		getPage: false,
		getDetailById: false,
		getAll: false,
		count: false,
		getDetailPage: true
	}
};

