exports.config = {
	aditionalOption: {
		add: true,
		addBatch: false,
		deleteById: true,
		deleteBatch: true,
		updateById: true,
		updateBatch: true,
		getById: true,
		getPage: true,
		getDetailById: false,
		getAll: false,
		count: false,
		getDetailPage: false
	},
	dictionary: {
		add: true,
		addBatch: false,
		deleteById: true,
		deleteBatch: true,
		updateById: true,
		updateBatch: true,
		getById: true,
		getPage: true,
		getDetailById: false,
		getAll: false,
		count: false,
		getDetailPage: false
	},
	fieldInfo: {
		add: true,
		addBatch: false,
		deleteById: true,
		deleteBatch: true,
		updateById: true,
		updateBatch: true,
		getById: true,
		getPage: true,
		getDetailById: false,
		getAll: false,
		count: false,
		getDetailPage: false
	},
	moduleS: {
		add: true,
		addBatch: false,
		deleteById: true,
		deleteBatch: true,
		updateById: true,
		updateBatch: true,
		getById: true,
		getPage: true,
		getDetailById: false,
		getAll: false,
		count: false,
		getDetailPage: false
	},
	project: {
		add: true,
		addBatch: false,
		deleteById: true,
		deleteBatch: true,
		updateById: true,
		updateBatch: true,
		getById: true,
		getPage: true,
		getDetailById: false,
		getAll: false,
		count: false,
		getDetailPage: false
	},
	tableInfo: {
		add: true,
		addBatch: false,
		deleteById: true,
		deleteBatch: true,
		updateById: true,
		updateBatch: true,
		getById: true,
		getPage: true,
		getDetailById: false,
		getAll: false,
		count: false,
		getDetailPage: false
	},
	themeConfig: {
		add: true,
		addBatch: false,
		deleteById: true,
		deleteBatch: true,
		updateById: true,
		updateBatch: true,
		getById: true,
		getPage: true,
		getDetailById: false,
		getAll: false,
		count: false,
		getDetailPage: false
	},
	validator: {
		add: true,
		addBatch: false,
		deleteById: true,
		deleteBatch: true,
		updateById: true,
		updateBatch: true,
		getById: true,
		getPage: true,
		getDetailById: false,
		getAll: false,
		count: false,
		getDetailPage: false
	}
};

