INSERT INTO `railway_ck`.`damage_repository`
(`order_detail_id`,
`order_no`,
`detect_time`,
`detect_stuff`,
`damage_type`,
`damage_level`,
`damage_detail`,
`damage_code`,
`damage_old`,
`damage_old_id`,
`receiving_unit`,
`receiving_user`,
`remark`,
`receiving_workarea_info`,
`deal_status`,
`import_status`,
`check_equipment`,
`analysis_result`,
`is_delete`,
`create_time`,
`update_time`,
`operator`,
`cancel`,
`audit_status`,
`last_detect_time`,
`delete_time`)
VALUES
(1,
'',
'',
1,
1,
1,
'',
'',
<{damage_old: }>,
<{damage_old_id: }>,
<{receiving_unit: }>,
<{receiving_user: }>,
<{remark: }>,
<{receiving_workarea_info: }>,
<{deal_status: }>,
<{import_status: }>,
<{check_equipment: }>,
<{analysis_result: }>,
<{is_delete: }>,
<{create_time: }>,
<{update_time: }>,
<{operator: }>,
<{cancel: }>,
<{audit_status: }>,
<{last_detect_time: }>,
@);
