exports.config = {
	backendConfig: {
		add: true,
		addBatch: false,
		deleteById: true,
		deleteBatch: false,
		updateById: true,
		updateBatch: false,
		getById: false,
		getPage: false,
		getDetailById: false,
		getAll: false,
		count: false,
		getDetailPage: true
	},
	casscader: {
		add: true,
		addBatch: false,
		deleteById: true,
		deleteBatch: false,
		updateById: true,
		updateBatch: false,
		getById: false,
		getPage: false,
		getDetailById: false,
		getAll: false,
		count: false,
		getDetailPage: true
	},
	checkbox: {
		add: true,
		addBatch: false,
		deleteById: true,
		deleteBatch: false,
		updateById: true,
		updateBatch: false,
		getById: false,
		getPage: false,
		getDetailById: false,
		getAll: false,
		count: false,
		getDetailPage: true
	},
	enumInfo: {
		add: true,
		addBatch: false,
		deleteById: true,
		deleteBatch: false,
		updateById: true,
		updateBatch: false,
		getById: false,
		getPage: false,
		getDetailById: false,
		getAll: false,
		count: false,
		getDetailPage: true
	},
	frontendConfig: {
		add: true,
		addBatch: false,
		deleteById: true,
		deleteBatch: false,
		updateById: true,
		updateBatch: false,
		getById: false,
		getPage: false,
		getDetailById: false,
		getAll: false,
		count: false,
		getDetailPage: true
	},
	projectConfig: {
		add: true,
		addBatch: false,
		deleteById: true,
		deleteBatch: false,
		updateById: true,
		updateBatch: false,
		getById: false,
		getPage: false,
		getDetailById: false,
		getAll: false,
		count: false,
		getDetailPage: true
	},
	tableEnum: {
		add: true,
		addBatch: false,
		deleteById: true,
		deleteBatch: false,
		updateById: true,
		updateBatch: false,
		getById: false,
		getPage: false,
		getDetailById: false,
		getAll: false,
		count: false,
		getDetailPage: true
	},
	tableInfo: {
		add: true,
		addBatch: false,
		deleteById: true,
		deleteBatch: false,
		updateById: true,
		updateBatch: false,
		getById: false,
		getPage: false,
		getDetailById: false,
		getAll: false,
		count: false,
		getDetailPage: true
	}
};

