public decimal? Time{ get; set;}
public decimal? OpenCnt{ get; set;}
public decimal? LoadTime{ get; set;}
public decimal? PhoneCnt{ get; set;}
public decimal? PhoneRate{ get; set;}
public decimal? SmsBntCnt{ get; set;}
public decimal? SmsBntCntRate{ get; set;}
public decimal? SmsCnt{ get; set;}
public decimal? SmsCntRate{ get; set;}
public decimal? SubmitBntCnt{ get; set;}
public decimal? SubmitBntCntRate{ get; set;}
public decimal? FormBntCnt{ get; set;}
public decimal? FormBntCntRate{ get; set;}
public decimal? StopTime{ get; set;}
public decimal? TermName{ get; set;}
public decimal? PromoterName{ get; set;}
public decimal? Principal{ get; set;}
public decimal? BusinessType{ get; set;}
public decimal? ProductName{ get; set;}
